-- 0005_resize_embedding_768.sql — OPTIONAL embedding column resize.
--
-- Apply ONLY for deployments using a 768-dim embedding provider (e.g.
-- ollama + nomic-embed-text). Deployments using the OpenAI default
-- (1536 dims) should NOT apply this file. See ADR 0001 § Decision 5
-- and `docs/deployment.md` § "Phase 2 — applying the MCP edge function".
--
-- Apply timing matters:
--   * Best — apply BEFORE any thoughts are captured. Zero data impact.
--   * Acceptable — apply AFTER captures, accepting that all existing
--     `embedding` values will be set to NULL (the alter-column type
--     change cannot in-place convert a 1536-vector to 768-vector
--     correctly; truncation would distort cosine similarity). After
--     this migration, run a re-embed pass against the new provider
--     (e.g. via a one-shot script that calls the capture path or
--     directly updates rows with new embeddings) before relying on
--     semantic search results.
--   * Wrong — apply AFTER captures and skip re-embedding. Searches
--     will return zero rows because the `is not null` guard in
--     `match_thoughts` filters them out. This is loud-fail behavior
--     by design.
--
-- This migration:
--   1. Drops the HNSW index (it is typed against the column's old dim
--      and cannot be altered in place).
--   2. Drops the `match_thoughts` function (its parameter type is
--      `extensions.vector(1536)`, which would conflict).
--   3. Resizes the column to vector(768), nulling existing values.
--   4. Recreates the HNSW index against the new dim.
--   5. Recreates `match_thoughts` with the new parameter signature.
--
-- Other dim variants (1024 for Cohere, 512 for Voyage, etc.) follow
-- this same template — copy and edit the dim literal in three places
-- (the alter column, the match_thoughts arg type, and any embedding
-- length expectations downstream).

begin;

-- 1. Drop the old HNSW index.
drop index if exists public.thoughts_embedding_hnsw_idx;

-- 2. Drop the old match_thoughts function (parameter type changes).
drop function if exists public.match_thoughts(
  extensions.vector(1536),
  int,
  float,
  uuid,
  public.thought_scope[]
);

-- 3. Resize the embedding column. Existing values become NULL.
--
-- We use `using null::extensions.vector(768)` rather than letting
-- Postgres attempt an implicit cast, which would fail at the dim
-- mismatch. Explicit nulling is the correct semantic — these
-- embeddings were generated by a different model and are not
-- meaningful in the new vector space.
alter table public.thoughts
  alter column embedding type extensions.vector(768)
  using null::extensions.vector(768);

-- 4. Recreate the HNSW index with the new dim.
create index thoughts_embedding_hnsw_idx
  on public.thoughts using hnsw (embedding extensions.vector_cosine_ops);

-- 5. Recreate match_thoughts. Identical body and grants to
--    0004_match_thoughts.sql; only the query_embedding parameter type
--    changes from vector(1536) to vector(768).
create or replace function public.match_thoughts(
  query_embedding   extensions.vector(768),
  match_count       int                     default 10,
  match_threshold   float                   default 0.5,
  filter_project_id uuid                    default null,
  filter_scopes     public.thought_scope[]  default null
)
returns table (
  id                uuid,
  content           text,
  scope             public.thought_scope,
  type              public.thought_type,
  project_id        uuid,
  author_user_id    uuid,
  similarity        float,
  created_at        timestamptz,
  last_verified_at  timestamptz,
  tags              text[]
)
language sql
security invoker
stable
set search_path = ''
as $$
  select
    t.id,
    t.content,
    t.scope,
    t.type,
    t.project_id,
    t.author_user_id,
    1 - (t.embedding operator(extensions.<=>) query_embedding) as similarity,
    t.created_at,
    t.last_verified_at,
    t.tags
  from public.thoughts t
  where t.embedding is not null
    and (filter_project_id is null or t.project_id = filter_project_id)
    and (filter_scopes     is null or t.scope = any(filter_scopes))
    and 1 - (t.embedding operator(extensions.<=>) query_embedding) > match_threshold
  order by t.embedding operator(extensions.<=>) query_embedding
  limit greatest(match_count, 0);
$$;

grant execute on function public.match_thoughts(
  extensions.vector(768),
  int,
  float,
  uuid,
  public.thought_scope[]
) to authenticated;

commit;
